### ISSUE TITLE
Add support for hostAliases

### ISSUE THREAD

**Issue by denisgarciaglobal** [gruntwork-io/helm-kubernetes-services#111]
**Describe the solution you'd like**
We are looking at adding entries to /etc/hosts of our pods. We'd like to take advantage of the hostAliases configuration we can add to a deployment (container spec)

**Describe alternatives you've considered**
We have considered not using Kubernetes configuration and adding those entries to our Docker images directly, but it is much less 

**Additional context**
Example of Kubernetes configuration

```
spec:
  [...]
  template:
    [...]
    spec:
      hostAliases:
        - ip: 10.1.2.3
          hostnames:
            - domain.name1.com
            - domain.name2.com
```

How it could look like in terraform
```
   hostAliases = {
      "10.1.2.3" = ["domain1.com", "domain2.com"]
      "10.1.2.4" = ["domain3.com"]
      "10.1.2.5" = ["domain4.com"]
  }
```
