### ISSUE TITLE
k8s-service: Add ability to use subPath to mount an individual file to a pod via configMaps

### ISSUE THREAD

**Issue by bobalong79** [gruntwork-io/helm-kubernetes-services#115]
Currently, the `k8s-service` helm chart does not provide the ability to define a file in a `ConfigMap` and mount it into an existing directory containing other files in the pod, e.g.

**ConfigMap**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  app-config.json: |
    {
      "environment": "uat"
    }
```

**Chart configMaps**
```
configMaps:
  my-configmap:
    as: volume
    mountPath: /usr/share/nginx/html/assets/json/app-config.json
    subPath: app-config.json
    items:
      app-config.json:
        filePath: app-config.json
```
This is a feature request to add support for that by utilizing `volumeMount.subPath`
