### ISSUE TITLE
Validation error on io.k8s.api.networking.v1.IngressBackend

### ISSUE THREAD

**Issue by paul-pop** [gruntwork-io/helm-kubernetes-services#117]
**Describe the bug**
With the introduction of capabilities introspection (#114) the spec for the ingress backend has not been updated accordingly to match the new API versions (in my case `networking.k8s.io/v1`) so an error is thrown for invalid spec:

```
Error: UPGRADE FAILED: error validating "": error validating data: 
[ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, 
ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```

The correct spec for this version can be found at https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressBackend

**To Reproduce**
Enable an ingress (see example below of values.yml) and run on Kubernetes >= 1.19.

```yml
containerPorts:
  http:
    port: 80

service:
  ports:
    app:
      port: 80

ingress:
  enabled: true
  path: /*
  servicePort: app
  hosts:
    - test.foo.com
```

**Expected behavior**
The ingress should be managed correctly by the chart for the given API version and be created in the cluster.

**Nice to have**
- [x] Terminal output

**Additional context**
There might be other breaking changes that were introduced in `networking.k8s.io/v1`, the only one I stumbled upon is the backend.

The change we need to make here is to move from:

```yml
          - path: ...
            backend:
              serviceName: ...
              servicePort: ... # this accepts both a number and a string
```

to:
```yml
          - path: ...
            backend:
              service:
                name: ...  # previous serviceName
                port:      # previous servicePort - the new values are mutually exclusive so the chart probably needs to be updated to accept either port name or port number
                  name: ...
                  number: ...
```
