### ISSUE TITLE
Add sessionAffinity ClientIP to k8s-service

### ISSUE THREAD

**Issue by tdharris** [gruntwork-io/helm-kubernetes-services#123]
**Describe the solution you'd like**
We are needing to ensure that connections from a particular client are passed to the same Pod each time for some period. We would like to approach this with `service.spec.sessionAffinity = ClientIP` (the default is `None`).

I believe the `service.yaml` definition would need to be enhanced to optionally include `sessionAffinity`:
```yaml
apiVersion: v1
kind: Service
metadata:
  ...
spec:
  selector:
    ...
  ports:
    ...
  sessionAffinity: ClientIP
```

And to specify a timeout:
```yaml
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
```

**Describe alternatives you've considered**
We've considered manually adjusting as needed, but would like to be able to set within the helm chart values.

**Additional context**
- See Kubernetes Service documentation of [sessionAffinity](https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies):

  > "If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client's IP addresses by setting service.spec.sessionAffinity to "ClientIP" (the default is "None"). You can also set the maximum session sticky time by setting service.spec.sessionAffinityConfig.clientIP.timeoutSeconds appropriately. (the default value is 10800, which works out to be 3 hours)."
- See [aws-cloud-map-mcs-controller-for-k8s spec definition](https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/blob/21585172c6e5979c09b3d4c4ae9d0944601ac5f1/config/crd/bases/multicluster.x-k8s.io_serviceimports.yaml#L81-L102) for more details on `sessionAffinity` and `sessionAffinityConfig`.
