### ISSUE TITLE
Ingress TLS block does not match the spec

### ISSUE THREAD

**Issue by shenal** [gruntwork-io/helm-kubernetes-services#34]
Ingress TLS block does not match the k8s Ingress spec and fails on deploy

Example values:
```yaml
ingress:
  enabled: true
  path: /
  hosts:
    - test-app.com
  servicePort: 80
  tls:
    - secretName: test-app-tls
      hosts:
      - test-app.com
```

Incorrectly rendered template
```yaml
# Source: k8s-service/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-test-app
  labels:
    gruntwork.io/app-name: test-app
    # These labels are required by helm. You can read more about required labels in the chart best
practices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    app.kubernetes.io/name: test-app
    helm.sh/chart: k8s-service-0.0.1-replace
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  tls:
    hosts:
    - test-app.com
    secretName: test-app-tls

  rules:
    - host: "test-app.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: release-name-test-app
              servicePort: 80
```
