### ISSUE TITLE
Add support for flexible environment variable settings

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/helm-kubernetes-services#59]
e.g being able to specify:

```
    spec:
      containers:
      - image: foobar:latest
        name: go-test-monitor-container
        imagePullPolicy: Always
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENTITY_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid 
```
