### ISSUE TITLE
[k8s-services chart] Add support for custom Kubernetes objects

### ISSUE THREAD

**Issue by paul-pop** [gruntwork-io/helm-kubernetes-services#81]
A lot of the times you need to work with custom Kubernetes objects or other objects/extensions of the Kubernetes ecosystem that are not yet supported in this chart.

Would be good to allow injecting an entire Kubernetes object (or several) inside the chart.

My use case is probably pretty standard. I use an external secret management store and I want to map the secrets found there into K8s secrets. For that, I use [external secrets](https://github.com/godaddy/kubernetes-external-secrets) which defines its own object called `ExternalSecret`. Currently, I need to apply this YML file before installing the chart which can be problematic. 

Here' an example of how I would see it working:

```yml
# Contents of templates/customobjects.yaml
{{- /*
If the operator configures the customObjects input variable, then create custom resources based on the given
definitions. If a list of definitions is provided, separate them using the YAML separator so they can all be executed
from the same template file.
*/ -}}

{{- if .Values.customObjects.enabled -}}
{{- range $name, $value := .Values.customObjects.definitions }}
---
{{ $value }}
{{- end }}
{{- end }}
```

```yml
# Sample values.yml passed in
customObjects:
  enabled: true
  definitions:
    custom_configmap: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: example
      data:
        flag: true
    custom_secret: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: example
      type: Opaque
      data:
        username: dXNlcm5hbWU=
```

I raised a draft PR to show how this works (I've tested it and it's all good). If you're happy with the approach I can write some tests and get it merged.
